### ISSUE TITLE
OOPS! issue should point to the file extended file

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#100]
After finishing ennumerating the pitfall summary, you should say something like:
"An extended evaluation file can be browsed in the OnToology bundle: OnToology/nameOfOntologyFolder.owl/evaluation/oopsEval.html

**Comment by ahmad88me** [comment]
@dgarijo 
This issue already there :smile:  https://github.com/OnToology/OnToology/issues/59
