### ISSUE TITLE
login with delicias

### ISSUE THREAD

**Issue by mariapoveda** [OnToology/OnToology#104]
@dgarijo should we allow login with delicias account for those that do not have a github one but want to regenerate vocab?

**Comment by ocorcho** [comment]
I would prefer not to do such an ad-hoc thing. Supporting single sign-on is ok, with GitHub and/or any other Auth provider.

**Comment by dgarijo** [comment]
I am against doing this. If we want to regenerate vocab, then we should add the means to vocab for doing it so, independently from Ontoology.

**Comment by mariapoveda** [comment]
I not sure about managing vocab.ld from 2 different systems you would need to handle communication between them and concurrency problems. My choice would be centralizing it through Ontoology and having as requisite to have a github account if someone wants to regenerate.

**Comment by dgarijo** [comment]
Since this is an old issue and there has not been progress, I am closing it
