### ISSUE TITLE
Empty repo list

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#105]
I have the "test" repo, but my list of repositories appears empty. Is this because a redeployment?
I attach an image
![sin titulo](https://cloud.githubusercontent.com/assets/1520666/7960632/5015ea12-0a02-11e5-831c-4e7bc2506fa5.png)

**Comment by ahmad88me** [comment]
@dgarijo if you added the repo while you are logged in, it should also added it to your user on the server. if you mean you added the repo before and now it is not showing at all, it depends on when you added it, because I did dropped the database around one week ago.

**Comment by dgarijo** [comment]
I see. I'll close the issue then.
