### ISSUE TITLE
Running vocab.linkeddata

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#108]
When I run the Jar file, I got this message: no main manifest attribute

**Comment by ahmad88me** [comment]
@dgarijo @mariapoveda

**Comment by dgarijo** [comment]
Ok, it turns out that we hadn't prepared the app to be executable by jar. I'll create one by improving the POM file and send it to you

**Comment by ahmad88me** [comment]
@dgarijo  it would be great, thanks :+1:
