### ISSUE TITLE
Unable to login with Github and grant permissions 

### ISSUE THREAD

**Issue by nandana** [OnToology/OnToology#118]
When I tried "Login through Github", I get the attached error. It might be related to issue #117 but I guess it is not the same because @dgarijo was able to login whereas I couldn't. 

![keyerror at _login_get_access-page-001](https://cloud.githubusercontent.com/assets/204855/8454955/5e47ee4a-2001-11e5-975e-cee5a8d6654d.jpg)
![keyerror at _login_get_access-page-002](https://cloud.githubusercontent.com/assets/204855/8454758/245a4012-2000-11e5-8a7f-246095a88a68.jpg)
![keyerror at _login_get_access-page-003](https://cloud.githubusercontent.com/assets/204855/8454761/286dd89e-2000-11e5-8046-7e5517ff7069.jpg)
![keyerror at _login_get_access-page-004](https://cloud.githubusercontent.com/assets/204855/8454765/2cb0ef9a-2000-11e5-929f-201789565499.jpg)
![keyerror at _login_get_access-page-005](https://cloud.githubusercontent.com/assets/204855/8454770/310c0f66-2000-11e5-9828-8a5a571cf44d.jpg)
![keyerror at _login_get_access-page-006](https://cloud.githubusercontent.com/assets/204855/8454773/33e4e19a-2000-11e5-91fe-59ff9465d126.jpg)

**Comment by ahmad88me** [comment]
@nandana Can you try now

**Comment by nandana** [comment]
Hi, now the login / permissions work for me. I could add a repo etc too. I actually couldn't find one of my repos with an ontology but I will try one with an ontology if I can recall a repo.
There is still a small issue though. When I sign it, the attached message is shown (though I think everything works fine). 
![screenshot from 2015-07-01 15 45 56](https://cloud.githubusercontent.com/assets/204855/8456123/9dee4a00-2009-11e5-87f7-c2c57cc116c4.png)

**Comment by ahmad88me** [comment]
Thank @nandana for the feedback, this happen when you click on refresh/reload. which is the same as asking for permission (similar to what a hacker would do to gain access for your account on your machine). I will redirect to the main page instead of printing this msg. Thanks Nandada

**Comment by ahmad88me** [comment]
@nandana and please do not hesitate to open more issue if you find any, thanks

**Comment by nandana** [comment]
Thanks for the quick fix! I will try with a repo with an ontology to provide more feedback!

The tool looks great by the way, all the best for your defence and keep up the good work!

**Comment by ahmad88me** [comment]
Many thank @nandana :smile_cat:
