### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by SerPablo** [OnToology/OnToology#119]
![login](https://cloud.githubusercontent.com/assets/2526093/8458324/c374148c-2016-11e5-9287-751873e17134.png)

**Comment by SerPablo** [comment]
This error appears when i push the login button on the main page on the URL : http://ontoology.linkeddata.es/

That does not appear on the URL : http://54.172.63.231/

**Comment by ahmad88me** [comment]
@SerPablo Fixed :+1:
