### ISSUE TITLE
Error when adding a repo that is not mine

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#120]
I tried to add Maria's repo (already watched). And I got this error:
404 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Not Found'}404 {u'documentation_url': u'https://developer.github.com/v3/repos/collaborators/#add-collaborator', u'message': u'Not Found'}

Also, it gives another error when attempting to remove from my watchlist.

**Comment by ahmad88me** [comment]
@dgarijo was this when you were using ontoology.linkeddata.es?

**Comment by dgarijo** [comment]
Yes. 
Now I get an error but I manage to watch it:
Error, ; not an ethical attempt

**Comment by ahmad88me** [comment]
@dgarijo where you accessing the tool with ontoology.linkeddata.es or with the IP, because now, the tool should only be accessed through ontoology.linkeddata.es as the session variables of each will be different. I also make it redirect to the main page instead showing this error, let me know if you faced a similar thing afterwards, many thanks

**Comment by dgarijo** [comment]
I still get the error:
404 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Not Found'}404 {u'documentation_url': u'https://developer.github.com/v3/repos/collaborators/#add-collaborator', u'message': u'Not Found'}
When watching the repo via ontoology.linkeddata.es. But the repo is added to my watchlist.
I also get an error when deleting it, but it is deleted.

**Comment by ahmad88me** [comment]
@dgarijo are you sure about this error, because this is a github error that happen when adding a collaborator to a repository. or do you mean a similar error with 404

**Comment by dgarijo** [comment]
I go to ontoology.linkeddata.es. I log in. I try to watch mariapoveda/ontoTest. Then I get the error, but the repo is added to my watchlist

**Comment by ahmad88me** [comment]
@dgarijo I thought this error when deleting the repo. This error happen (according to Github) when you do not have enough permission on the repo, I added a friendly error. If the error already watched before, nothing will change. I think it will not add it if Github prints this report. To make sure, can you do a test for me. first remove the webhook from the repo, then remove ontoology from the collaborators then add Maria's  repo
