### ISSUE TITLE
Initial push by Widoco

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#123]
In the ontology I used [1] has a rdfs:label with it's name. It was not picked by the tool. Do you use any predicates like dc:title to guess the name of the ontology? I could change it in widoco.conf so I think it is not a big problem. I couldn't find how to do the same with OOPS! report though. 

[1] https://raw.githubusercontent.com/nandana/ontoology-test/master/alm-istack.owl

**Comment by ahmad88me** [comment]
@dgarijo I do not parse the owl yet. I thought Widoco will generate a config file instead. But I can parse the OWL for rdfs:label or dc:title.

**Comment by dgarijo** [comment]
The initial push by Ontoology should use the option to pick up the metadata from the ontology, instead of the default config file. The problem right now is that on that initial push, Widoco doesn't generate that config file. I will look into it.

**Comment by ahmad88me** [comment]
Widoco now generate the config file
