### ISSUE TITLE
ValidationError (User.OUser:None) (String value is too long: ['username'])

### ISSUE THREAD

**Issue by valentinedwv** [OnToology/OnToology#125]
ValidationError at /login_get_access
ValidationError (User.OUser:None) (String value is too long: ['username'])

Username is 32 characters long
# 

EmbeddedDocumentField <class 'mongoengine.fields.EmbeddedDocumentField'>

fields [(<mongoengine.base.fields.ObjectIdField object at 0x7f09af916310>, None),
 (<mongoengine.fields.StringField object at 0x7f09af910650>,
  u'**************_+**_**_@gmail.com'),
 (<mongoengine.fields.StringField object at 0x7f09af910790>, None),
 (<mongoengine.fields.StringField object at 0x7f09af910850>, None),
 (<mongoengine.fields.EmailField object at 0x7f09af910910>,
  u'**_***********_+**_***@gmail.com'),
 (<mongoengine.fields.StringField object at 0x7f09af910a10>,
  u'pbkdf2_sha256$12000$WAYN1jTwfQZP$9hC4Km5lmX7CaGEwX0CSVDKe227LcnJ3Pfcmeng4F9c='),
 (<mongoengine.fields.BooleanField object at 0x7f09af910b50>, False),
 (<mongoengine.fields.BooleanField object at 0x7f09af910c50>, True),
 (<mongoengine.fields.BooleanField object at 0x7f09af910d90>, False),
 (<mongoengine.fields.DateTimeField object at 0x7f09af910e90>,
  datetime.datetime(2015, 7, 7, 17, 10, 41, 130752, tzinfo=<UTC>)),
 (<mongoengine.fields.DateTimeField object at 0x7f09af910f50>,
  datetime.datetime(2015, 7, 7, 17, 10, 41, 130647, tzinfo=<UTC>)),
 (<mongoengine.fields.ListField object at 0x7f09af916110>, []),
 (<mongoengine.fields.ListField object at 0x7f09af916850>, [])]

self <OUser: ***************+******@gmail.com>

GenericEmbeddedDocumentField <class 'mongoengine.fields.GenericEmbeddedDocumentField'>

field <mongoengine.fields.ListField object at 0x7f09af916850>

value []

clean True

error ValidationError(String value is too long,)

pk None

message 'ValidationError (User.OUser:None) '

**Comment by ahmad88me** [comment]
@valentinedwv Thank you for contacting us, I will be looking into this issue

**Comment by ahmad88me** [comment]
This bug is related to the older version of OnToology and never happened again. I'll assume it is fixed. When it happen again, we will be able to investigate as we have a better logs now.
