### ISSUE TITLE
Errors reported in issues are not informative

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#133]
This is what we see in the issue:
validating The Documentation of the file be/AboutBE-1.0.rdf if not generated The Documentation of the file be/AboutBE.rdf if not generated The Documentation of the file be/Corporations/AboutCorporations.rdf if not generated.

What we should show is a detail of the log produced by the tool that failed when producing the doc, evaluation or diagrams.

**Comment by dallemang** [comment]
The errors with the About files (I suspect) stem from that fact that these ontologies are basically empty; they have metadata for standards purposes, and they have imports that organize all the ontologies that come together, but no content in their own right.
