### ISSUE TITLE
preview of evaluation goes to a test ontology.

### ISSUE THREAD

**Issue by mariapoveda** [OnToology/OnToology#138]
https://rawgit.com/dgarijo/VideoGameOntology/master/OnToology/old/GameOntologyv1.owl/evaluation/oopsEval.html

The links from the repo https://github.com/dgarijo/VideoGameOntology/issues go to the test ontology preview.

**Comment by ahmad88me** [comment]
@mariapoveda can you explain what do you mean by test ontology preview

**Comment by mariapoveda** [comment]
The title of the ontology in the preview html

**Comment by ahmad88me** [comment]
@mariapoveda Ya I can see it now, I will check it

**Comment by ahmad88me** [comment]
@dgarijo This is called by Widoco as below, should I add another flag?

java -jar  -Dfile.encoding=utf-8 /home/ubuntu/Widoco/JAR/widoco-0.0.1-jar-with-dependencies.jar -oops  -ontFile /home/ubuntu/temp/mpovedavillalon@gmail.com/GameOntologyv3.owl -outFolder /home/ubuntu/temp/mpovedavillalon@gmail.com/OnToology/GameOntologyv3.owl/evaluation

**Comment by dgarijo** [comment]
I don't have much contest for this issue. Apparently, it is not taking the ontology metadata appropriately. Could you please update the last widoco JAR and let me know?

**Comment by ahmad88me** [comment]
@dgarijo I will do so and provide a feedback
