### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'unicode'

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#139]
This is the error I get when I update any of my current Ontologies.

**Comment by ahmad88me** [comment]
@mariapoveda I'm getting 500 for OOPS webservice. I'm not sure if this is caused by OnToology.

"Server returned HTTP response code: 500 for URL: http://oops-ws.oeg-upm.net/rest"

**Comment by dgarijo** [comment]
I am not getting 500. I get a not allowed when submitting the request,
which means it's on.
However, OnToology should work even if OOPS! returns a 500, right?
Best,
Dani

2015-09-09 21:29 GMT+02:00 Ahmad Alobaid <notifications@github.com>:

**Comment by ahmad88me** [comment]
@dgarijo I found the 500 error in the logs. and you are right that it should work regardless of that error.

**Comment by dgarijo** [comment]
@ahmad88me Maybe it was down for a period of time... sometimes they do maintenance and restart the servers :S

**Comment by ahmad88me** [comment]
@dgarijo I think it is the case, because it works when disabling the Evaluation from the configuration file. I'm investigating the issue more, so if OOPS is under maintenance, OnToology will inform the user about it

**Comment by mariapoveda** [comment]
Do you still have problems with oops? it is being stressed out ...

On Wed, Sep 9, 2015 at 10:28 PM, Ahmad Alobaid <notifications@github.com>
wrote:

> @dgarijo <https://github.com/dgarijo> I think it is the case, because it
> works when disabling the Evaluation from the configuration file. I'm
> investigating the issue more, so if OOPS is under maintenance, OnToology
> will inform the user about it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OnToology/OnToology/issues/139#issuecomment-139036786>
> .
>



-- 
María Poveda Villalón

PhD student
Ontology Engineering Group (OEG)
Universidad Politécnica de Madrid
Madrid, Spain

e-mail: mpoveda@fi.upm.es
website: http://purl.org/net/mpoveda
<http://delicias.dia.fi.upm.es/~mpoveda/>
blog: http://thepetiteontologist.wordpress.com/

**Comment by ahmad88me** [comment]
@mariapoveda Sorry for the very late reply, yes it is resolved :+1:
