### ISSUE TITLE
Errors should be more informative.

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#141]
Right now the errors are designed for developers, not for users.
For example: <unknown>:1:49: syntax error, unsupported operand type(s) for +: 'NoneType' and 'unicode', etc.

Instead, we should say something like: "Error while generating documentation/diagrams, etc". The ontology is not correct/is too big, etc.

**Comment by ahmad88me** [comment]
Yes sure, this should be changed

**Comment by ahmad88me** [comment]
The new fix now sends an email to the admin. If it is an input error, informative error messages will be displayed
