### ISSUE TITLE
Limit somehow the diagram size

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#142]
For example, for pipauwel/ifcOWL    the tool has been showing"drawing diagrams for IFC2X3_TC1.ttl" for a couple of hours.
If the diagram reaches a particular size or the number of concepts is more than, let's say, 100, do not draw it or add restrictions.

**Comment by ahmad88me** [comment]
With the new servers, OnToology can handle big ontologies, it even works with DBpedia's ontology. So I'll close this case
