### ISSUE TITLE
Create a proper testing repository

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#143]
In my "test" repository I have gathered the ontologies that have produced errors. We should see which repositories are currently added but with an error in their ontologies and then use them as a source for testing capabilities.

Furthermore, we should contact the responsible for each failed ontology and let them know when they are fixed.

**Comment by ahmad88me** [comment]
@dgarijo for sure, I will take a look tomorrow on this

**Comment by ahmad88me** [comment]
Done

**Comment by dgarijo** [comment]
Where is this repo?

**Comment by ahmad88me** [comment]
@dgarijo https://github.com/ahmad88me/target/tree/master/problems

**Comment by dgarijo** [comment]
Awesome. Can I submit more vocabularies, so we end up with a nice collection of conflicting vocs?

**Comment by ahmad88me** [comment]
Sure
