### ISSUE TITLE
<unknown>:1:49: syntax error happening for pmidford/arachb_ontology

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#144]
spent a couple of days to solve it

**Comment by ahmad88me** [comment]
Solved it. the problem was that the ontology is too large that oops return an error 502

**Comment by ahmad88me** [comment]
@mariapoveda I'm suspecting that is the reason, currently I put an error message "Ontology is too big for OOPS". What do you think

**Comment by mariapoveda** [comment]
Ok for now.

On Wed, Nov 11, 2015 at 12:16 PM, Ahmad Alobaid <notifications@github.com>
wrote:

> @mariapoveda <https://github.com/mariapoveda> I'm suspecting that is the
> reason, currently I put an error message "Ontology is too big for OOPS".
> What do you think
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OnToology/OnToology/issues/144#issuecomment-155739050>
> .
>



-- 
María Poveda Villalón

PhD student
Ontology Engineering Group (OEG)
Universidad Politécnica de Madrid
Madrid, Spain

e-mail: mpoveda@fi.upm.es
website: http://purl.org/net/mpoveda
<http://delicias.dia.fi.upm.es/~mpoveda/>
blog: http://thepetiteontologist.wordpress.com/

**Comment by ahmad88me** [comment]
@mariapoveda @dgarijo should I send him an email now that his problem is fixed

**Comment by dgarijo** [comment]
@ahmad88me If it works, then I would force a pull request from ontoology (no refresh needed) and then send the user an email saying that we have solved the issue and now there is a pull request with the vocabulary. Thanks!!
