### ISSUE TITLE
Collaborators cannot use the tool

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#149]

**Comment by ahmad88me** [comment]
@dgarijo if you get time, can you create a test project and add me as a collaborator to check this error. and also tell me the permission you provided me with

**Comment by dgarijo** [comment]
I have created the repo: https://github.com/dgarijo/OnToologyTests
I have added you (ahmad88me) as a collaborator

**Comment by ahmad88me** [comment]
@dgarijo what is the permission you provided me with

**Comment by ahmad88me** [comment]
solved
