### ISSUE TITLE
OnToology does not save my configuracion from WUI

### ISSUE THREAD

**Issue by mariapoveda** [OnToology/OnToology#159]
I set the evaluation and diagrams off for all the ontologies in mariapoveda/sdh-ontos-mp, click "save" and when I open it back their state is "on".

**Comment by ahmad88me** [comment]
@mariapoveda   I remember that this API is failing from Github side. It works if you try again (multiple times). But ya we need to have a proper handling

**Comment by ahmad88me** [comment]
@mariapoveda seems like I created another issue with the same description https://github.com/OnToology/OnToology/issues/230

anyways it is resolved today, feel free to re-open it if it is not solved ;)
