### ISSUE TITLE
I cannot refresh a published ontology in OnToology

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#194]
If I try to update the html once the ontology is published in OnToology, the html is not refreshed. Therefore the user doesn't know how to update this html. If a vocabulary is published, i think that the button should be "refresh published vocabulary" in the GUI (or something like that), so the html is refreshed. If we pointed to Github, this issue would be solved automatically.

**Comment by ahmad88me** [comment]
Republishing is working now
