### ISSUE TITLE
Suggestions on column names for the reserved names column

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#202]
w3id URL should be w3id URI.

the w3id should point to the https version of the uri, not the http. For example, point to https://w3id.org/def/test instead of http://w3id.org/def/test

The w3id uri should be clickable.

The "repository" and "columns" are not yet filledt with the appropriate info from the ontology.

**Comment by ahmad88me** [comment]
@dgarijo for the last issue, this is because of the newly added value. so if you publish now it will be filled.

fixed: (merge request #207)
