### ISSUE TITLE
Generating documentation in multiple languages 

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#223]
At the moment we only support English.
However, Widoco supports English, Spanish and Portuguese (and Italian, if I'm not mistaken). 
We should be able to allow producing the documentation in several languages in OnToology. This could be added in the configuration file.

**Comment by ahmad88me** [comment]
@dgarijo 
it would be something like 
widoco.jar [other flags] -lang en es it

**Comment by paoespinozarias** [comment]
Hi guys,
I used Widoco to generate the documentation in Spanish, but will be really nice if you add this feature in OnToology.
Thanks :)

**Comment by ahmad88me** [comment]
This issue is similar to https://github.com/OnToology/OnToology/issues/385. So I'll close this one
