### ISSUE TITLE
I want to know what is the status of my repository

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#225]
Right now there is nothing telling me what is going on, and I find that frustrating as a user

**Comment by ahmad88me** [comment]
@dgarijo Do you mean in the bright look(new look) or the dark look(the live one)? Now it is showing more information in the status, you can check it out in the live one ;)

**Comment by dgarijo** [comment]
Ok thanks!!
Please take this into account for the bright one as well before closing this issue :)
