### ISSUE TITLE
Loading ontologies in profile page

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#239]
If the path to the configuration file contains a space, the ontologies in that repo won't show.

**Comment by mariapoveda** [comment]
I don't have any space in saref-ext

**Comment by ahmad88me** [comment]
Maybe the one that you have in mind does not have a space, but this one "OnToology/SAREF4BLD/RawRDF/IFC-device-Raw copy.rdf/OnToology.cfg" for example has a space, which was causing the issue, anyway it is solved now. I'll check the publishing to see if the same thing happen there as well. @mariapoveda

**Comment by mariapoveda** [comment]
sure, I only checked the folders

**Comment by mariapoveda** [comment]
thanks for solving this

**Comment by ahmad88me** [comment]
@mariapoveda anytime Doctor 😉
