### ISSUE TITLE
Documentation section overwritten 

### ISSUE THREAD

**Issue by idafensp** [OnToology/OnToology#242]
When a section of the documentation (e.g. abstract) is modified, and a new change is pushed on the ontology, the section file gets overwritten.

**Comment by ahmad88me** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [widoco-rewrite-all](https://trello.com/c/vFaIPsUE/6-widoco-rewrite-all)

**Comment by ahmad88me** [comment]
Solved ;) 
commit 4738dab2973999d1fda4bf9b46330a06ea4aed4e
