### ISSUE TITLE
E-mail is public but not seen by OnToology

### ISSUE THREAD

**Issue by vcharpenay** [OnToology/OnToology#293]
My E-mail is public on my Github profile but whenever I try to connect ([Login through Github](http://ontoology.linkeddata.es/login)), I get the following message:

```
You have to make you email public and try again.
```

As I had two e-mails on my profile, I tried to delete one to see if there was any change. After I did it, I got a 500 response code with the following message:

```
IndexError at /get_access_token

list index out of range

Request Method: 	GET
Request URL: 	http://54.172.63.231/get_access_token?code=cf1a67bc859f90034f86&state=vYj3xGJqI
Django Version: 	1.7
Exception Type: 	IndexError
Exception Value: 	

list index out of range

Exception Location: 	/home/ubuntu/OnToology/OnToology/views.py in get_access_token, line 140
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
Python Path: 	

['/home/ubuntu/OnToology/OnToology/..',
 '/home/ubuntu/OnToology',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']

Server time: 	Wed, 26 Apr 2017 12:36:27 +0000
...
```

**Comment by ahmad88me** [comment]
Hi @vcharpenay , I applied the fix, now it should work. 

If you need to double check if the email is public or not, you can see the below screenshot. 

![public email github](https://cloud.githubusercontent.com/assets/6922709/25474585/0c41b852-2b34-11e7-8e6f-58086e0bb8ed.png)

**Comment by ahmad88me** [comment]
@vcharpenay We assume that this issue is resolved, if not feel free to re-open it again so we can investigate it further, 
Best,
