### ISSUE TITLE
Problem accessing repository

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#345]
Mariano has reported the following issue:
When he clicks on his repo, this message appears:
404 {u'documentation_url': u'https://developer.github.com/v3/repos/contents/#update-a-file', u'message': u'Not Found'}

Not sure what could be the cause.

**Comment by ahmad88me** [comment]
I sent an email to Mariano asking him how did he got the error.

**Comment by ahmad88me** [comment]
I still didn't get a reply from him and there has been some improvements on the tools in that area. So, I'll close this issue.
