### ISSUE TITLE
Problem with ontology

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#350]
Mariano reports the following issue:
"Cuando pulso en el icono de generar documentación, se queda atascado en
drawing diagrams for: dul-dolce-zero-en-espannol.rdf
Creo que se lía porque mi ontología importa a otras dos y, a su vez, una de ellas importa a la otra."

There may be a problem in the diagrams when doing cyclic references between ontologies.

**Comment by dgarijo** [comment]
Update: the process ends, but it takes a very long time. Maybe we could do something to limit or restrict this kind of behavior

**Comment by GeorgFerdinandSchneider** [comment]
Hi!

it might be that I have a similar problem. I added a repository (GeorgFerdinandSchneider/bot) 4 days ago. Ontoology started working but now stays since several days at 28 % progress.

Best

Georg

**Comment by dgarijo** [comment]
None of the ontologies seem problematic.
@ahmad88me could you have a look?
@GeorgFerdinandSchneider, have you tried refreshing manually from the configuration?

**Comment by ahmad88me** [comment]
@GeorgFerdinandSchneider @dgarijo The issue related to George's repository was due to a syntax error in SAREF4BLDGAlignment.ttl. Now the issue is solved. George, you can go to the progress page to see the details [here](http://ontoology.linkeddata.es/progress).

**Comment by ahmad88me** [comment]
@dgarijo I forked his repos and it took only few minutes to regenerate everything. It could be that his repo contained a syntax error and then he pushed a new ontology version fixing the syntax error.

**Comment by dgarijo** [comment]
Thanks @ahmad88me 
@GeorgFerdinandSchneider please give it a try now and let us know if you have further problems!
