### ISSUE TITLE
Two # in URIs

### ISSUE THREAD

**Issue by mariapoveda** [OnToology/OnToology#365]
when generating the documentation (at least with w3id) two # appear in the URI:

http://ontoology.linkeddata.es/publish/saref4bldg/index-en.html#https://w3id.org/def/saref4bldg#Outlet

Is this done due to some rewriting or Widoco does directly?

**Comment by dgarijo** [comment]
This could be due to the fact that there is no URI specified as ontology URI in WIDOCO. Therefore it recognizes it as an external URL and uses the full w3id instead of the hash. It looks like a configuration issue on OnToology's side.

**Comment by ahmad88me** [comment]
@dgarijo for each line in the htaccess file, OnToology replaces 'RewriteBase' with 'RewriteBase /publish/vocabularyname'. Is something changed in Widoco that this is not longer that case?

**Comment by dgarijo** [comment]
If you don't set the right IRI name for the ontology, WIDOCO won't point to the local path ("#"). Instead, it will add the URI. It is a configuration issue

**Comment by ahmad88me** [comment]
@dgarijo How to set the right IRI name for the ontology ?

**Comment by mariapoveda** [comment]
If it is published with w3id you have it when they chose it. If not, could be complicated.

The one in owl:Ontology, or one of the prefixes define, or the base one, or the empty one, or none of them...

**Comment by dgarijo** [comment]
If the ontology has the vann:preferedNamespaceURI. Or in the config file.
I have generated the documentation locally. The URLs are generated fine by default (loading metadata from the ontology).

**Comment by ahmad88me** [comment]
@dgarijo @mariapoveda So Daniel how do you think this can be solved? I think this might be related to the way widoco is being called?

OnToology use the configuration file if it exists, otherwise it will generate it. So OnToology does not regenerate the configuration file it already exists.

**Comment by dgarijo** [comment]
I would suggest rerunning it again @ahmad88me. I cannot see a discrepancy on the ontology URIs, and other published ontologies (e.g., http://ontoology.linkeddata.es/publish/test/index-en.html#Activity or http://ontoology.linkeddata.es/publish/HXA/index-en.html#%E4%BF%AE%E5%BE%A9) seem to be fine. Maybe in this ontology when it was first invoked it didn't have the "getOntologyMetadata", or something similar.

I have tried WIDOCO with the original ontology (in https://github.com/mariapoveda/saref-ext) and everything is generated properly

**Comment by ahmad88me** [comment]
Thank you daniel, I'll close it then.
