### ISSUE TITLE
Access to my own github account after git clone

### ISSUE THREAD

**Issue by ponnou** [OnToology/OnToology#377]
Hello all,

I cloned the OnToology project repo and ran it into my virtual machine, so I can have access to the web application but when I tried to enter my own repo here : 

![image](https://user-images.githubusercontent.com/13155852/34056820-91d30122-e1a2-11e7-9981-3e979e5cfa1d.png)

I have a 404 error.

Thanks in advance for your help.

**Comment by ahmad88me** [comment]
Hi @ponnou , 

    The tool user (`OnToologyUser`) is hardcoded in the code (should be changed to an environment variable). Also you need to fill the environment variables in the virtual environment. Let us know if the problem persists after your changes (feel free to create a pull request of your changes). 

Cheers,

**Comment by ponnou** [comment]
Hello @ahmad88me 

I am using apache 2 so as the documentation mention I cannot use environment variable but I overwrote the local WSGI file localwsgi.py like you can see below :  

 ![image](https://user-images.githubusercontent.com/13155852/34114565-1da6f2fe-e3e1-11e7-961d-53ce2ff35007.png)

And this is the log I got

![image](https://user-images.githubusercontent.com/13155852/34114665-5a9f940e-e3e1-11e7-9611-b3d5e7e9f49c.png)

What do you think ?
Thank you in advance for your reply.

**Comment by ahmad88me** [comment]
Hi @ponnou ,

    You need to fill in the rest of the variables (e.g. _client_id_login_, _db_username_, ... etc.).  _client_id_login_, _client_id_public_, and _client_id_private_ holds the ids of applications on GitHub (that are created for that purpose). Note that we host OnToology application as well [here](http://ontoology.linkeddata.es). You can use it without hosting OnToology on your server. 

Cheers,
