### ISSUE TITLE
syntax error on generating documentation 

### ISSUE THREAD

**Issue by PabloFdez** [OnToology/OnToology#379]
Hi, I'm trying to upload my ontology but i always get a syntax error, idk why because it's a Protégé generated ontology.

https://github.com/PabloFdez/Ontool2

Thanks!!

**Comment by ahmad88me** [comment]
@PabloFdez  We have a problem with this syntax (owl/xml) at the moment [see #367], but the rest of the tools actually supports it. We will fix it soon. 

Cheers,

**Comment by PabloFdez** [comment]
Oh Thanks!
I tried RDF syntax and works perfectly!

**Comment by ahmad88me** [comment]
We are glad that it works for you, Enjoy!
