### ISSUE TITLE
Configure Ar2dtool so the nodes appear with prefixes and showing the right class  diagram

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#39]
Ask @dgarijo or @idafensp for help if you cannot generate the proper diagram.
Additional filtering like isDefinedBy may be required.

**Comment by ahmad88me** [comment]
@idafensp I used the below configuration file to ignore isDefinedBy, but it still include it in the generated diagrams.
configuration file: https://raw.githubusercontent.com/ahmad88me/target/master/auton/diagrams/ar2dtool-class.conf/ar2dtool-class.conf

the generated diagram: https://raw.githubusercontent.com/ahmad88me/target/master/auton/diagrams/ar2dtool-class.conf/org/daniel.owl.png

Thank you

**Comment by idafensp** [comment]
The correct syntax for ignoreElementList is:
ignoreElementList=[<http://www.w3.org/2000/01/rdf-schema#subClassOf,http://www.w3.org/2000/01/rdf-schema#isDefinedBy>];

Try this and let me know.

**Comment by ahmad88me** [comment]
@idafensp I tried the same, but still shows idDefinedBy in the generated diagram
