### ISSUE TITLE
Removing a repository and adding it again does not work

### ISSUE THREAD

**Issue by ocorcho** [OnToology/OnToology#395]
I have recently removed the repository opencitydata/cultura-ocio-agenda-eventos-actividades, and I have tried to add it again, but it does not seem to be added correctly, and it does not appear under my repositories

**Comment by ahmad88me** [comment]
@ocorcho as a workaround, you can try to fork it to a github user (e.g. for your user) and then add it. The reason is because repos under organizations are not fully supported (A need to review the new APIs of GitHub).
