### ISSUE TITLE
Previsualization generation of a repository with submodules

### ISSUE THREAD

**Issue by jperez4** [OnToology/OnToology#396]
The idea is that if we have one repository for each vocabulary instead of having a main repository with all the vocabularies within, be able to make a repository with submodules where each submodule is a independent vocabulary repository and to generate a previsualization of all the repositories together.

**Comment by ahmad88me** [comment]
Thanks for the suggestion @jperez4 , we are looking into that and we believe it is an important feature to support.

**Comment by ahmad88me** [comment]
Hi @jperez4 
The simple submodules now are supported. 
see : https://ahmad88me.github.io/demo-submod/
for the repo: https://github.com/ahmad88me/demo-submod
