### ISSUE TITLE
Allowing the configuration of the rewritebase for .htaccess

### ISSUE THREAD

**Issue by ocorcho** [OnToology/OnToology#398]
Not sure if this issue needs to be made available here or in the Widoco repository, since I am not sure about which tool generates the .htaccess file that is useful to upload in a Web server. It would be nice anyway to be able to configure the rewritebase to be declared inside the .htaccess file, probably in a configuration file

**Comment by dgarijo** [comment]
This has to be done in WIDOCO. I will open an issue there.
It is not hard to do, but I need to find the time.
