### ISSUE TITLE
Improve step by step tutorial

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#417]
All the publishing is not included in the tutorial.
The functionality of menus is not explained. We have received some complaints on the menus not being understandable, so at least we should add a tutorial. I can contribute to this.

**Comment by dgarijo** [comment]
I improved the tutorial slightly, but haven't added publication yet.

**Comment by mariapoveda** [comment]
I've created a new branch (tutorail) with a suggestion for the tutorial
