### ISSUE TITLE
Did not work to me - add hook exception: 'ref' in the logs

### ISSUE THREAD

**Issue by vroddon** [OnToology/OnToology#425]
I see it as ready...

![image](https://user-images.githubusercontent.com/5434597/43880894-a0011e7c-9bed-11e8-9963-7ffaccc60a0b.png)
...
but no pull request has been made whatsoever

![image](https://user-images.githubusercontent.com/5434597/43880932-c95193e2-9bed-11e8-90ee-0bf94f860b5b.png)

thanks!

**Comment by ahmad88me** [comment]
Seems like GitHub made a change in the webhook requests body. It should be fixed now. 

You can generate everything by clicking on the regenerate all button (see the screenshot below). 

![screen shot 2018-08-09 at 3 13 54 pm](https://user-images.githubusercontent.com/6922709/43902287-f6e483b8-9be9-11e8-925c-3828744d846e.png)
