### ISSUE TITLE
Add how to cite OnToology

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#432]

**Comment by dgarijo** [comment]
Here you should add the citation to https://doi.org/10.1016/j.websem.2018.09.003
But you should also link the pdf. I have it here: http://dgarijo.com/publications.html

**Comment by ahmad88me** [comment]
Thanks Daniel, now it is added [here](http://ontoology.linkeddata.es/publications)

**Comment by dgarijo** [comment]
@ahmad88me,
the science direct link takes me to a paywall. Can you also add the link to the pdf preprint? I have it here: http://dgarijo.com/papers/JWSsupporting.pdf

**Comment by dgarijo** [comment]
Also, please clarify that they should use the JWS citation. It's very confusing when I want to cite a project and I only see a list of publications. I would like to know which one is the one that is preferred by the authors.
And you are missing the citation of the software (Zenodo DOI)

**Comment by ahmad88me** [comment]
Yes, it is true. I just added it 👍

**Comment by dgarijo** [comment]
Please change the sentence: "To cite the work, please use the first one"
to be:
"To cite OnToology please use the first reference of the list below"
Thanks!!

And in the software section, please add: "To cite the latest software version of OnToology, please use the following reference".
Also, the link should redirect to the latest Zenodo DOI, not the Github repo: https://doi.org/10.5281/zenodo.1317785

Question: Have you linked OnToology GitHub with Zenodo? If not, you should, as that way every time you do a release you will get a new DOI (although https://doi.org/10.5281/zenodo.1317785 will always point to the latest)

**Comment by ahmad88me** [comment]
I push the changes, but now I can't merge the pull request due to internal storage issue in GitHub. Once it is fixed, I'll do the merge request and update the server

**Comment by ahmad88me** [comment]
Done. @dgarijo I prefer to do the publishing manually as Zenodo asks for too much permissions. Thanks for the suggestions 😉
