### ISSUE TITLE
The name of the ontology is not shown in the HTML documentation

### ISSUE THREAD

**Issue by marianofl1971** [OnToology/OnToology#443]
The title of the [LIS ontology](https://github.com/marianofl1971/lis) is not shown, in spite of the ```dc:title``` annotation is used.

**Comment by dgarijo** [comment]
Widoco uses http://purl.org/dc/terms/title and http://
purl.org/dc/elements/1.1/title
I tested out
https://raw.githubusercontent.com/marianofl1971/lis/master/lis.owl and it
reads the title fine.

**Comment by ahmad88me** [comment]
@marianofl1971 I updated the Widoco to the latest version. It is working with OnToology as well, can you clarify more where it does not show (which part).

**Comment by ahmad88me** [comment]
@marianofl1971 I'll close this issue. you can re-open it if the issue still persists

**Comment by marianofl1971** [comment]
I agree.

**Comment by marianofl1971** [comment]
I have seen another ontology where the name does not appear in the title of the sections:

http://iot.linkeddata.es/def/wot/index-en.html

**Comment by dgarijo** [comment]
@marianofl1971,
I just ran WIDOCO with that ontology and the name of the section looks good to me (see screenshot below). Probably they did some manual editing to change the name. Or maybe it's the way OnToology calls WIDOCO, @ahmad88me 

![screenshot_2019-02-12 ontology model for web of things](https://user-images.githubusercontent.com/1520666/52665942-b7e03200-2ec1-11e9-96b7-e1eb4a70044c.png)

**Comment by ahmad88me** [comment]
@dgarijo There is a separate issue for this one: https://github.com/OnToology/OnToology/issues/449
I answered you in that thread
