### ISSUE TITLE
The license of the ontology is not shown in the HTML documentation

### ISSUE THREAD

**Issue by marianofl1971** [OnToology/OnToology#444]
The license is not shown in the [LIS ontology](https://github.com/marianofl1971/lis), in spite of the annotation ```dcterms:license``` has been used.

**Comment by mariapoveda** [comment]
@dgarijo is this an issue with licensius?

**Comment by dgarijo** [comment]
Unless you use a certain flag licensius won't be invoked. I had to take that decision because the service is often offline. By default widoco looks at dcterms info about license

**Comment by mariapoveda** [comment]
Thanks @dgarijo 

Actually, I see the badge with the license at https://w3id.org/def/lis @marianofl1971  is this issue solved?

**Comment by ahmad88me** [comment]
@marianofl1971 I downloaded the documentation in the specified repo, I can see that license is showing (see this screenshot). 
<img width="647" alt="screen shot 2019-02-04 at 17 49 06" src="https://user-images.githubusercontent.com/6922709/52215573-5d354d80-28a5-11e9-845b-b835ed97ccf6.png">

**Comment by ahmad88me** [comment]
@marianofl1971 I assume that you are no longer having this issue, please reopen and add more details if you still have this issue.

**Comment by marianofl1971** [comment]
I added manually the license.

**Comment by ahmad88me** [comment]
-licensius flag to be added

**Comment by ahmad88me** [comment]
@marianofl1971 I was not aware of the new change in Widoco. I added that flag and this should be solved now. Let us know for any further issues.
