### ISSUE TITLE
Errors are not shown in LIS ontology

### ISSUE THREAD

**Issue by marianofl1971** [OnToology/OnToology#445]
According to OnToology, [LIS ontology](https://github.com/marianofl1971/lis) has errors, but when chicking their link, OnToology remains at the same page.

**Comment by ahmad88me** [comment]
@marianofl1971 Can you elaborate which links?

**Comment by marianofl1971** [comment]
OnToology works fine for the last version of the ontology. If find a similar problem further, I will open another issue.
