### ISSUE TITLE
The name of the ontology does not appear in the title of the sections

### ISSUE THREAD

**Issue by marianofl1971** [OnToology/OnToology#449]
I have seen another ontology where the name does not appear in the title of the sections:

http://iot.linkeddata.es/def/wot/index-en.html

**Comment by ahmad88me** [comment]
@marianofl1971 Can you share the url of the ontology that you used?

**Comment by marianofl1971** [comment]
You can access to the source code of the ontology through the link that I have provided in my comment, and clicking any of the icons in the _download serialization_ section at the beginning of the HTML document.

**Comment by ahmad88me** [comment]
@dgarijo I think Mariano is referring to this: 
![screen shot 2019-02-13 at 09 32 07](https://user-images.githubusercontent.com/6922709/52697778-79568000-2f72-11e9-87b3-817311bc4101.png)

**Comment by ahmad88me** [comment]
@marianofl1971 @dgarijo I just copied the ontology into a test repo, and I don't see the problem (https://ahmad88me.github.io/testmariano/OnToology/wot.rdf/documentation/index-en.html). I have two guesses here:
1. That was the name of the ontology at the beginning. So Widoco fetch the meta data and store them (see here: https://github.com/ahmad88me/testmariano/blob/master/OnToology/wot.rdf/documentation/wot.rdf.widoco.conf). After the second update, OnToology will see that there is a meta info file and will use it (which contains the wrong name.). Maybe Garijo have an input here.
2. It could be something with the old Widoco, but we didn't see a similar issue, so this is unlikely. 
 
To solve this you can update the meta info directly if you have written the documentation and don't want them to be overwritten. Or, you can delete the documentation (or the meta file) to have a new documentation. Also OnToology is using a newer version of Widoco (updated yesterday) just in case it was related to the older version of Widoco.

**Comment by ahmad88me** [comment]
This is tested lately at it works. So I will close it
