### ISSUE TITLE
Issue with content negotiation for hash-based ontologies 

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#459]
The issue is related to the new way Widoco is handling the content negotiation.

**Comment by dgarijo** [comment]
New way? There has been no changes regarding content negotiation...
I detected a bug and fixed it, but that's it.

**Comment by ahmad88me** [comment]
Hola @dgarijo , it might to an older change in Widoco for handling content negotiation that I don't take it into account (not sure though). Could be the hash vs slash URLs.
OnToology updates the .htaccess generate by Widoco for the content negotiation (to work with GitHub pages). I'll know for sure when I look further into it 😉.

**Comment by dgarijo** [comment]
Hash vs slash redirections have different content negotiation structure because of how the slash redirect works. But it has always been like that ;)

**Comment by ahmad88me** [comment]
See: https://github.com/protegeproject/protege/issues/890

**Comment by ahmad88me** [comment]
The issue seems to be from Protege side. Hence, I will clause this issue.
