### ISSUE TITLE
Anchor links do not work

### ISSUE THREAD

**Issue by ednaru** [OnToology/OnToology#461]
I need to create anchor links within a page when explaining some concepts in the ontology (the ontology has not been published yet), these do not work.

**Comment by mariapoveda** [comment]
Could you ellaborate a bit more? which page? generated with Widoco?

**Comment by ednaru** [comment]
In previous versions of my documentation I had "El concepto principal de este vocabulario es el de [esagm:Evento](#Evento)" and it worked, in latter versions it stopped working. I changed it to: 
El concepto principal de este vocabulario es el de [esagm:Evento](index-es.html#http://vocab.ciudadesabiertas.es/def/sector-publico/agenda-municipal#Evento) and now it works.

**Comment by ahmad88me** [comment]
@ednaru I noticed a bug in the content negotiation, I solved it partially a few days ago, but I am not sure if it is the cause.
From my understanding it is solved, so I will close it. Feel free to reopen if the same issue occur again. 
Thanks for reporting.
