### ISSUE TITLE
Some consistency errors/bugs in HTML

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#538]
- [x] The layout changes and the css are inconsistent (some I think are not loading fine)
- [x] I cannot see how to generate landing pages.
- [x] Many things like "OPub" or "repos" are not clear in meaning.
- [x] Some instructions like the enable github pages are outdated (you can have everything in the main branch)
- [x] There are new services which are cool, but are a little disconnected, like syntax validation.
- [ ] When errors are generated (e.g. by OOPS reports, I cannot see why)
- [x] Repos and Profile do essentially the same thing.

**Comment by ahmad88me** [comment]
I added check box to keep track.

**Comment by ahmad88me** [comment]
OnToology only supports github pages using the `gh-pages` branch.
