### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#546]
Here is my review of the UI: 

  - Landing page:
    - [x] I like the what Ontoology is and how to use it. It's missing a link to the tutorial.
    - [x] Tweets -> too big. Why not at the side?
    - [x] Latest repos -> too low, and wide.
    - [x] Easy to confuse the bottom header with the rest. Make it lower, and different color.
  - [x] Step by Step -> Tutorial.
  - [x] About seems outdated.
  - [x] About should have the publications.
  - [x] Publications should include a way to get the bib entry.
  - [x] Publications should be in about
  - [x] I do not understand Syntax validator. It should not be one of the tabs. If someone does not understand an error, then we should place this when reporting this error.
  - [x] From "my profile", no link is working.
  - [x] The text is in general not well aligned to the center.
  - [x] From the messages, e.g. "Soon you will find a PR in your repo", it's not clear what to do next.
  - [x] I don't know what manipulate repo means.
  - [x] What is the difference between runs and history ❓  (reply:  they refer to the same page.)
  - [x] JSON-LD label is not correct. WIDOCO generates JSON-LD, OnToology generated **context** files.
  - [x] I would have My repositories first. Then, My published ontologies. And then active jobs. Then, log out
  - [x] I don't get what profile does. I would remove it.
  - [x] MyProfile should be MyOntologies, and I should be taken there when I click on it. On hover, I still get the menu.
- [x] Same size in logos (i.e., GitHub, bootstrap).

**Comment by ahmad88me** [comment]
I changed the comment to add check boxes.

**Comment by ahmad88me** [comment]
Done
