### ISSUE TITLE
getmetadata for Widoco

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#57]

**Comment by ahmad88me** [comment]
@dgarijo should I use -getOntologyMetadata with -confFile ? 
-in the README file it was mentions to use one of them only, if so, why getOntologyMetadata is only used once. [I read the readme but I got kinda confused]

**Comment by dgarijo** [comment]
The first time Widoco is run for a vocabulary, it should be called with -getOntologyMetadata , and not with -confFile. However, Ontoology should create a config file and push it for the next iterations. I will add an issue to Widoco to produce the config file when  the tool gets the metadata from the ontology.

**Comment by ahmad88me** [comment]
solved by Widoco newer version that produce the configuration file
