### ISSUE TITLE
Add reference to SPRINT project in projects the about section

### ISSUE THREAD

**Issue by ocorcho** [OnToology/OnToology#582]
It would be relevant to add the project SPRINT to the list of projects in http://ontoology.linkeddata.es/about.  The following text would be good:

In SPRINT, Ontoology was extended in order to support ontology development efforts in the context of the Shift2Rail Interoperability Framework, and has been used for the documentation of ontologies being developed in this context.

**Comment by mariapoveda** [comment]
Added Drugs4covid and easytv.
