### ISSUE TITLE
Error in content negotiation (RDF/XML)

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#667]
In an ontology published with OnToology (https://w3id.org/def/digitaltwin) I see the content negotiation is not correct. 
It works for TTL but for RDF/XML, the HTML is returned. As a result, the ontology does not load in protege.

This used to work fine @ahmad88me, has there been a change?

**Comment by ahmad88me** [comment]
@dgarijo I guess it is related to this one  https://github.com/dgarijo/Widoco/issues/643
I will investigate this further

**Comment by dgarijo** [comment]
Oh, but that one was addressed! Please add the latest jar :)

**Comment by ahmad88me** [comment]
@dgarijo  @Salva5297  fixed. 

I tested the fix here.
```
curl -v -L -H "Accept: application/rdf+xml" https://w3id.org/def/ahmad-WoT-DT-ontology-test
```

**Comment by dgarijo** [comment]
Awesome!

**Comment by Salva5297** [comment]
Thank you very much!
