### ISSUE TITLE
Refine error page when a repo is already watched.

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#68]
The current error is:
Msg: {u'documentation_url': u'https://developer.github.com/v3/repos/hooks/#create-a-hook', u'message': u'Validation Failed', u'errors': [{u'message': u'Hook already exists on this repository', u'code': u'custom', u'resource': u'Hook'}]}

**Comment by dgarijo** [comment]
This issue has been closed, but I still see this message:
Msg: 422 {u'documentation_url': u'https://developer.github.com/v3/repos/hooks/#create-a-hook', u'message': u'Validation Failed', u'errors': [{u'message': u'Hook already exists on this repository', u'code': u'custom', u'resource': u'Hook'}]} 
Maybe it has not been redeployed yet? (that's why I don't reopen)

**Comment by ahmad88me** [comment]
@dgarijo ya sorry forgot to deploy, not tested
