### ISSUE TITLE
No pull request is created

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#70]
Even though I have one repository called "test"

**Comment by ahmad88me** [comment]
@dgarijo are you clicking on the repo in the profile page?

**Comment by dgarijo** [comment]
Yes. It appears empty

**Comment by dgarijo** [comment]
![error](https://cloud.githubusercontent.com/assets/1520666/7784141/5286d6e4-015b-11e5-8e02-44fa87f55d4c.png)
Screenshot

**Comment by dgarijo** [comment]
I redid the webhook and now I can see it properly

**Comment by ahmad88me** [comment]
@dgarijo ya because (if I understood the issue correctly) it only keep track if the added repos (which in your case is not added because I drop the database for the new schema )

**Comment by dgarijo** [comment]
I redid the webhook and now I can see it. However there are no pull requests.

**Comment by ahmad88me** [comment]
@dgarijo What is the repo, so I can check it

**Comment by dgarijo** [comment]
dgarijo/test: https://github.com/dgarijo/test

**Comment by ahmad88me** [comment]
@dgarijo testing it now

**Comment by ahmad88me** [comment]
@dgarijo it was because a renaming the app on the server, now it is working and should work for your ontologies as well

**Comment by ahmad88me** [comment]
No fixed
