### ISSUE TITLE
Tried to add a new repo and it crashes

### ISSUE THREAD

**Issue by mariapoveda** [OnToology/OnToology#72]
![screen shot 2015-05-18 at 3 59 36 pm](https://cloud.githubusercontent.com/assets/5693576/7682268/211bd09c-fd77-11e4-97dd-43ec1e9b3cc0.png)

**Comment by ahmad88me** [comment]
@mariapoveda this is resolved right?

**Comment by mariapoveda** [comment]
yes. We must show our emails in the github profile. :-)

**Comment by ahmad88me** [comment]
@mariapoveda And now it prints a message to the user that he must make his email public. There is another way that does not require the email to be viewed, I put it in issues also 
https://github.com/OnToology/OnToology/issues/74
