### ISSUE TITLE
Table of Repos and Tools no more valid

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#76]
![screen shot 2015-05-20 at 4 47 36 pm](https://cloud.githubusercontent.com/assets/6922709/7728537/2ce7c742-ff10-11e4-8a62-dfb4d0cf519d.png)

@dgarijo @mariapoveda 

The tools for each repo isn't  valid anymore since we have now configuration file for each ontology rather than for each repo. I think there are two approaches:
1. Remove the tools columns
2. For each Repo, view the ontologies and tools used. 

Note that on the profile page, the table will show for each repo the ontologies belonging to that repo and the configuration of each

**Comment by dgarijo** [comment]
I vote for having an additional column that specifies the ontology being watched
In the example, you would have :
Repositoy                            Ontology                     Status ...(the rest of the oclumns go here)
mariapoveda/VoCampOnto nameOfTheOnto.owl Ready ...

**Comment by mariapoveda** [comment]
I think we agreed yesterday on combining panels (for repos) and tables
within panels (for ontologies) and the info would be only in the ontologies.

**Comment by dgarijo** [comment]
I don't understand

**Comment by mariapoveda** [comment]
You wasn't there xD

On Wednesday, May 20, 2015, Daniel Garijo <notifications@github.com> wrote:

> I don't understand
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OnToology/OnToology/issues/76#issuecomment-103922039>.
>


-- 
María Poveda Villalón

PhD student
Ontology Engineering Group (OEG)
Universidad Politécnica de Madrid
Madrid, Spain

e-mail: mpoveda@fi.upm.es
website: http://purl.org/net/mpoveda
<http://delicias.dia.fi.upm.es/~mpoveda/>
blog: http://thepetiteontologist.wordpress.com/

**Comment by dgarijo** [comment]
I know, but maybe you could ellaborate what you mean for me, please?
In any case, if you both decided on that decission, I'm fine with it...

**Comment by mariapoveda** [comment]
Panels and tables are elements from bootstrap. We can have one panel for
each repository and within it one table whith one row per ontology in the
repo.

On Wednesday, May 20, 2015, Daniel Garijo <notifications@github.com> wrote:

> I know, but maybe you could ellaborate what you mean for me, please?
> In any case, if you both decided on that decission, I'm fine with it...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OnToology/OnToology/issues/76#issuecomment-103922639>.
>


-- 
María Poveda Villalón

PhD student
Ontology Engineering Group (OEG)
Universidad Politécnica de Madrid
Madrid, Spain

e-mail: mpoveda@fi.upm.es
website: http://purl.org/net/mpoveda
<http://delicias.dia.fi.upm.es/~mpoveda/>
blog: http://thepetiteontologist.wordpress.com/

**Comment by dgarijo** [comment]
Perfect :+1:
