### ISSUE TITLE
Highlight new changes in documentation

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#79]
I'm not sure to include this in Widoco, OnToology or develop a separate tool of this. But I think this would be really helpful to check new documents without referring back to older versions of the same documentation. This will make the development process easier.

**Comment by dgarijo** [comment]
I was planning at some point to include it Widoco, but I don't think it should be part of Ontoology. Ontoology works with Github, where you can actually see the diff between two different versions. Hence, that info is not needed. it is already included

**Comment by ahmad88me** [comment]
@dgarijo But I think Github will show the difference with the html tags in it, which I guess not friendly. The idea came to me when I was reading about VoCol which target domain experts as well, which is not a target audience of OnToology. So I think no highlighting :smile:

**Comment by dgarijo** [comment]
You've got a point. It would be really nice to see a diff in a user friendly way, like highlighting stuff in the html. Ideally we should have it as a separate module. The input would be 2 different versions of the html/ontology and the output an html with the differences. Good idea. Let us first refine the current tool, wrap up the publication process and then explore this as future work. Does it make sense?

**Comment by ahmad88me** [comment]
@dgarijo si si :+1:
