### ISSUE TITLE
How to remove a repo/stop watching a repo?

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#81]
There should be an option when logging in in OnToology.
If you remove the webhook, the repo still would appear on the main page...

**Comment by ahmad88me** [comment]
@dgarijo ya because OnToology only subscribed to repo pushes only, Github APIs does not support changes in webhooks. I can add a new method, once used access his profile page, I can check if the webhook is still there and update the database accordingly. You think I should add it

**Comment by ahmad88me** [comment]
@dgarijo Or should be it be a button in the profile page to disable/ remove a repo

**Comment by dgarijo** [comment]
I think that there should be abutton in the profile page to remove/stop following a repo

**Comment by ahmad88me** [comment]
@dgarijo Noted, I created a new issue for this https://github.com/OnToology/OnToology/issues/83
