### ISSUE TITLE
For OOPS! how many issues 

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#82]
Since repos can have more than one ontology, should there be a single issue for all the ontologies (combined) or should there be an issue for each ontology.
@dgarijo @mariapoveda

**Comment by mariapoveda** [comment]
I think one issue for each ontology.

**Comment by dgarijo** [comment]
I agree: One issue for each ontology that has been changed.

**Comment by ahmad88me** [comment]
@dgarijo @mariapoveda Thanks, working on it now
