### ISSUE TITLE
New Organization flow

### ISSUE THREAD

**Issue by ahmad88me** [OnToology/OnToology#9]
## In case the repo belongs to an organization

Github does not allow even admins to create teams, but allow adding to existing team. so the new flow will be as below:
1- The system detects that this repo belongs to an organization.
2- Check if there is a team named 'Auton' associated with the provided repo.
3- If yes, and the user 'AutonUser' is part of the team then proceed with the rest of the normal repo flow
4- If no, Instruction will be shown inorder to continue with the flow.

**Comment by dgarijo** [comment]
This issue no longer applies
