### ISSUE TITLE
If no documentation exists (or has been deleted) widoco is not invoked correctly

### ISSUE THREAD

**Issue by dgarijo** [OnToology/OnToology#98]
It should be invoked with the option to get the metadata from the ontology. Currently it isn't. This may be on hold until I finish producing the config file for this option.

**Comment by ahmad88me** [comment]
@dgarijo 
yes, and it is the same as https://github.com/OnToology/OnToology/issues/57 
right?

**Comment by dgarijo** [comment]
Oh I thought the previous one was closed. Apologies

**Comment by ahmad88me** [comment]
@dgarijo its ok, a lot of issue makes us a little confused :smile:
